name: "test-local"
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
