name: "Update Pull Request"

on: pull_request

jobs:
  pr_update_title:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
